### ISSUE TITLE
Missing file code

### ISSUE THREAD

**Issue by 464hee** [ShengtianSang/AFMA#1]
from models.base import get_preprocessing_fn
from ..base import get_encoder
from ..base import SegmentationHead, ClassificationHead

**Comment by 464hee** [comment]
@ShengtianSang

**Comment by ShengtianSang** [comment]
Hi, thank you for the comments, and I've added the missing __inti__ part in the code and updated the old version. You can run the codes without installing SMP now. Thank you for your questions again.
